// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  DESKTOP-9QSNDR4
// DateTime: 12/06/2021 11:12:43
// UserName: Mateusz
// Input file <C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y - 12/06/2021 11:00:40>

// options: lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace mini_compiler
{
public enum Tokens {error=2,EOF=3,Program=4,Identifier=5,IntegerLiteral=6,
    DoubleLiteral=7,BoolLiteral=8,StringLiteral=9,Integer=10,Double=11,Bool=12,
    Hex=13,Assign=14,Or=15,And=16,BitwiseOr=17,BitwiseAnd=18,
    Equals=19,NotEquals=20,GreaterThan=21,GreaterOrEqual=22,LessThan=23,LessOrEqual=24,
    Plus=25,Minus=26,Multiply=27,Divide=28,Negate=29,BitwiseNegate=30,
    If=31,Else=32,While=33,Read=34,Write=35,Return=36,
    OpenBracket=37,CloseBracket=38,OpenCurl=39,CloseCurl=40,Semicolon=41,Comma=42,
    Dot=43};

public struct ValueType
#line 4 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
       {
	public int Integer;
	public string String;
	public double Double;
	public bool Bool;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[70];
  private static State[] states = new State[135];
  private static string[] nonTerms = new string[] {
      "start", "$accept", "declarations", "instructions", "declaration", "declarationInt", 
      "declarationDouble", "declarationBool", "instruction", "blockInstruction", 
      "expression", "ifInstruction", "whileInstruction", "inputInstruction", 
      "outputInstruction", "returnInstruction", "assignExpression", "logicalExpression", 
      "relationExpression", "addExpression", "mulExpression", "bitExpression", 
      "unaryExpression", "factorExpression", };

  static Parser() {
    states[0] = new State(new int[]{4,3},new int[]{-1,1});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{39,4});
    states[4] = new State(new int[]{10,111,11,119,12,127,39,-18,5,-18,26,-18,30,-18,29,-18,37,-18,6,-18,8,-18,7,-18,31,-18,33,-18,34,-18,35,-18,36,-18,2,-18,40,-18},new int[]{-3,5,-4,8,-5,109});
    states[5] = new State(new int[]{40,6});
    states[6] = new State(new int[]{3,7});
    states[7] = new State(-2);
    states[8] = new State(new int[]{39,11,5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44,31,75,33,83,34,89,35,96,36,105,2,107,40,-3},new int[]{-9,9,-10,10,-11,14,-17,16,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41,-12,74,-13,82,-14,88,-15,95,-16,104});
    states[9] = new State(-17);
    states[10] = new State(-19);
    states[11] = new State(-18,new int[]{-4,12});
    states[12] = new State(new int[]{40,13,39,11,5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44,31,75,33,83,34,89,35,96,36,105,2,107},new int[]{-9,9,-10,10,-11,14,-17,16,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41,-12,74,-13,82,-14,88,-15,95,-16,104});
    states[13] = new State(-27);
    states[14] = new State(new int[]{41,15});
    states[15] = new State(-20);
    states[16] = new State(-28);
    states[17] = new State(new int[]{14,18,17,-60,18,-60,27,-60,28,-60,25,-60,26,-60,19,-60,20,-60,21,-60,22,-60,23,-60,24,-60,15,-60,16,-60,41,-60,38,-60,42,-60});
    states[18] = new State(new int[]{5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44},new int[]{-17,19,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41});
    states[19] = new State(-29);
    states[20] = new State(new int[]{15,21,16,72,41,-30,38,-30,42,-30});
    states[21] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-19,22,-20,71,-21,62,-22,61,-23,60,-24,41});
    states[22] = new State(new int[]{19,23,20,52,21,63,22,65,23,67,24,69,15,-31,16,-31,41,-31,38,-31,42,-31});
    states[23] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-20,24,-21,62,-22,61,-23,60,-24,41});
    states[24] = new State(new int[]{25,25,26,54,19,-34,20,-34,21,-34,22,-34,23,-34,24,-34,15,-34,16,-34,41,-34,38,-34,42,-34});
    states[25] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-21,26,-22,61,-23,60,-24,41});
    states[26] = new State(new int[]{27,27,28,56,25,-41,26,-41,19,-41,20,-41,21,-41,22,-41,23,-41,24,-41,15,-41,16,-41,41,-41,38,-41,42,-41});
    states[27] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-22,28,-23,60,-24,41});
    states[28] = new State(new int[]{17,29,18,58,27,-44,28,-44,25,-44,26,-44,19,-44,20,-44,21,-44,22,-44,23,-44,24,-44,15,-44,16,-44,41,-44,38,-44,42,-44});
    states[29] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-23,30,-24,41});
    states[30] = new State(-47);
    states[31] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-23,32,-24,41});
    states[32] = new State(-50);
    states[33] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-23,34,-24,41});
    states[34] = new State(-51);
    states[35] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-23,36,-24,41});
    states[36] = new State(-52);
    states[37] = new State(new int[]{10,38,11,46,5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44},new int[]{-11,49,-17,16,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41});
    states[38] = new State(new int[]{38,39});
    states[39] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-23,40,-24,41});
    states[40] = new State(-53);
    states[41] = new State(-55);
    states[42] = new State(-57);
    states[43] = new State(-58);
    states[44] = new State(-59);
    states[45] = new State(-60);
    states[46] = new State(new int[]{38,47});
    states[47] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-23,48,-24,41});
    states[48] = new State(-54);
    states[49] = new State(new int[]{38,50});
    states[50] = new State(-56);
    states[51] = new State(new int[]{19,23,20,52,21,63,22,65,23,67,24,69,15,-33,16,-33,41,-33,38,-33,42,-33});
    states[52] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-20,53,-21,62,-22,61,-23,60,-24,41});
    states[53] = new State(new int[]{25,25,26,54,19,-35,20,-35,21,-35,22,-35,23,-35,24,-35,15,-35,16,-35,41,-35,38,-35,42,-35});
    states[54] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-21,55,-22,61,-23,60,-24,41});
    states[55] = new State(new int[]{27,27,28,56,25,-42,26,-42,19,-42,20,-42,21,-42,22,-42,23,-42,24,-42,15,-42,16,-42,41,-42,38,-42,42,-42});
    states[56] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-22,57,-23,60,-24,41});
    states[57] = new State(new int[]{17,29,18,58,27,-45,28,-45,25,-45,26,-45,19,-45,20,-45,21,-45,22,-45,23,-45,24,-45,15,-45,16,-45,41,-45,38,-45,42,-45});
    states[58] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-23,59,-24,41});
    states[59] = new State(-48);
    states[60] = new State(-49);
    states[61] = new State(new int[]{17,29,18,58,27,-46,28,-46,25,-46,26,-46,19,-46,20,-46,21,-46,22,-46,23,-46,24,-46,15,-46,16,-46,41,-46,38,-46,42,-46});
    states[62] = new State(new int[]{27,27,28,56,25,-43,26,-43,19,-43,20,-43,21,-43,22,-43,23,-43,24,-43,15,-43,16,-43,41,-43,38,-43,42,-43});
    states[63] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-20,64,-21,62,-22,61,-23,60,-24,41});
    states[64] = new State(new int[]{25,25,26,54,19,-36,20,-36,21,-36,22,-36,23,-36,24,-36,15,-36,16,-36,41,-36,38,-36,42,-36});
    states[65] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-20,66,-21,62,-22,61,-23,60,-24,41});
    states[66] = new State(new int[]{25,25,26,54,19,-37,20,-37,21,-37,22,-37,23,-37,24,-37,15,-37,16,-37,41,-37,38,-37,42,-37});
    states[67] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-20,68,-21,62,-22,61,-23,60,-24,41});
    states[68] = new State(new int[]{25,25,26,54,19,-38,20,-38,21,-38,22,-38,23,-38,24,-38,15,-38,16,-38,41,-38,38,-38,42,-38});
    states[69] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-20,70,-21,62,-22,61,-23,60,-24,41});
    states[70] = new State(new int[]{25,25,26,54,19,-39,20,-39,21,-39,22,-39,23,-39,24,-39,15,-39,16,-39,41,-39,38,-39,42,-39});
    states[71] = new State(new int[]{25,25,26,54,19,-40,20,-40,21,-40,22,-40,23,-40,24,-40,15,-40,16,-40,41,-40,38,-40,42,-40});
    states[72] = new State(new int[]{26,31,30,33,29,35,37,37,6,42,8,43,7,44,5,45},new int[]{-19,73,-20,71,-21,62,-22,61,-23,60,-24,41});
    states[73] = new State(new int[]{19,23,20,52,21,63,22,65,23,67,24,69,15,-32,16,-32,41,-32,38,-32,42,-32});
    states[74] = new State(-21);
    states[75] = new State(new int[]{37,76});
    states[76] = new State(new int[]{5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44},new int[]{-11,77,-17,16,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41});
    states[77] = new State(new int[]{38,78});
    states[78] = new State(new int[]{39,11,5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44,31,75,33,83,34,89,35,96,36,105,2,107},new int[]{-9,79,-10,10,-11,14,-17,16,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41,-12,74,-13,82,-14,88,-15,95,-16,104});
    states[79] = new State(new int[]{32,80,39,-61,5,-61,26,-61,30,-61,29,-61,37,-61,6,-61,8,-61,7,-61,31,-61,33,-61,34,-61,35,-61,36,-61,2,-61,40,-61});
    states[80] = new State(new int[]{39,11,5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44,31,75,33,83,34,89,35,96,36,105,2,107},new int[]{-9,81,-10,10,-11,14,-17,16,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41,-12,74,-13,82,-14,88,-15,95,-16,104});
    states[81] = new State(-62);
    states[82] = new State(-22);
    states[83] = new State(new int[]{37,84});
    states[84] = new State(new int[]{5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44},new int[]{-11,85,-17,16,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41});
    states[85] = new State(new int[]{38,86});
    states[86] = new State(new int[]{39,11,5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44,31,75,33,83,34,89,35,96,36,105,2,107},new int[]{-9,87,-10,10,-11,14,-17,16,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41,-12,74,-13,82,-14,88,-15,95,-16,104});
    states[87] = new State(-63);
    states[88] = new State(-23);
    states[89] = new State(new int[]{5,90});
    states[90] = new State(new int[]{41,91,42,92});
    states[91] = new State(-64);
    states[92] = new State(new int[]{13,93});
    states[93] = new State(new int[]{41,94});
    states[94] = new State(-65);
    states[95] = new State(-24);
    states[96] = new State(new int[]{9,102,5,17,26,31,30,33,29,35,37,37,6,42,8,43,7,44},new int[]{-11,97,-17,16,-18,20,-19,51,-20,71,-21,62,-22,61,-23,60,-24,41});
    states[97] = new State(new int[]{41,98,42,99});
    states[98] = new State(-66);
    states[99] = new State(new int[]{13,100});
    states[100] = new State(new int[]{41,101});
    states[101] = new State(-67);
    states[102] = new State(new int[]{41,103});
    states[103] = new State(-68);
    states[104] = new State(-25);
    states[105] = new State(new int[]{41,106});
    states[106] = new State(-69);
    states[107] = new State(new int[]{41,108});
    states[108] = new State(-26);
    states[109] = new State(new int[]{10,111,11,119,12,127,39,-18,5,-18,26,-18,30,-18,29,-18,37,-18,6,-18,8,-18,7,-18,31,-18,33,-18,34,-18,35,-18,36,-18,2,-18,40,-18},new int[]{-3,110,-4,8,-5,109});
    states[110] = new State(-4);
    states[111] = new State(new int[]{5,113,2,117},new int[]{-6,112});
    states[112] = new State(-5);
    states[113] = new State(new int[]{41,114,42,115});
    states[114] = new State(-8);
    states[115] = new State(new int[]{5,113,2,117},new int[]{-6,116});
    states[116] = new State(-9);
    states[117] = new State(new int[]{41,118});
    states[118] = new State(-10);
    states[119] = new State(new int[]{5,121,2,125},new int[]{-7,120});
    states[120] = new State(-6);
    states[121] = new State(new int[]{41,122,42,123});
    states[122] = new State(-11);
    states[123] = new State(new int[]{5,121,2,125},new int[]{-7,124});
    states[124] = new State(-12);
    states[125] = new State(new int[]{41,126});
    states[126] = new State(-13);
    states[127] = new State(new int[]{5,129,2,133},new int[]{-8,128});
    states[128] = new State(-7);
    states[129] = new State(new int[]{41,130,42,131});
    states[130] = new State(-14);
    states[131] = new State(new int[]{5,129,2,133},new int[]{-8,132});
    states[132] = new State(-15);
    states[133] = new State(new int[]{41,134});
    states[134] = new State(-16);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{4,39,-3,40,3});
    rules[3] = new Rule(-3, new int[]{-4});
    rules[4] = new Rule(-3, new int[]{-5,-3});
    rules[5] = new Rule(-5, new int[]{10,-6});
    rules[6] = new Rule(-5, new int[]{11,-7});
    rules[7] = new Rule(-5, new int[]{12,-8});
    rules[8] = new Rule(-6, new int[]{5,41});
    rules[9] = new Rule(-6, new int[]{5,42,-6});
    rules[10] = new Rule(-6, new int[]{2,41});
    rules[11] = new Rule(-7, new int[]{5,41});
    rules[12] = new Rule(-7, new int[]{5,42,-7});
    rules[13] = new Rule(-7, new int[]{2,41});
    rules[14] = new Rule(-8, new int[]{5,41});
    rules[15] = new Rule(-8, new int[]{5,42,-8});
    rules[16] = new Rule(-8, new int[]{2,41});
    rules[17] = new Rule(-4, new int[]{-4,-9});
    rules[18] = new Rule(-4, new int[]{});
    rules[19] = new Rule(-9, new int[]{-10});
    rules[20] = new Rule(-9, new int[]{-11,41});
    rules[21] = new Rule(-9, new int[]{-12});
    rules[22] = new Rule(-9, new int[]{-13});
    rules[23] = new Rule(-9, new int[]{-14});
    rules[24] = new Rule(-9, new int[]{-15});
    rules[25] = new Rule(-9, new int[]{-16});
    rules[26] = new Rule(-9, new int[]{2,41});
    rules[27] = new Rule(-10, new int[]{39,-4,40});
    rules[28] = new Rule(-11, new int[]{-17});
    rules[29] = new Rule(-17, new int[]{5,14,-17});
    rules[30] = new Rule(-17, new int[]{-18});
    rules[31] = new Rule(-18, new int[]{-18,15,-19});
    rules[32] = new Rule(-18, new int[]{-18,16,-19});
    rules[33] = new Rule(-18, new int[]{-19});
    rules[34] = new Rule(-19, new int[]{-19,19,-20});
    rules[35] = new Rule(-19, new int[]{-19,20,-20});
    rules[36] = new Rule(-19, new int[]{-19,21,-20});
    rules[37] = new Rule(-19, new int[]{-19,22,-20});
    rules[38] = new Rule(-19, new int[]{-19,23,-20});
    rules[39] = new Rule(-19, new int[]{-19,24,-20});
    rules[40] = new Rule(-19, new int[]{-20});
    rules[41] = new Rule(-20, new int[]{-20,25,-21});
    rules[42] = new Rule(-20, new int[]{-20,26,-21});
    rules[43] = new Rule(-20, new int[]{-21});
    rules[44] = new Rule(-21, new int[]{-21,27,-22});
    rules[45] = new Rule(-21, new int[]{-21,28,-22});
    rules[46] = new Rule(-21, new int[]{-22});
    rules[47] = new Rule(-22, new int[]{-22,17,-23});
    rules[48] = new Rule(-22, new int[]{-22,18,-23});
    rules[49] = new Rule(-22, new int[]{-23});
    rules[50] = new Rule(-23, new int[]{26,-23});
    rules[51] = new Rule(-23, new int[]{30,-23});
    rules[52] = new Rule(-23, new int[]{29,-23});
    rules[53] = new Rule(-23, new int[]{37,10,38,-23});
    rules[54] = new Rule(-23, new int[]{37,11,38,-23});
    rules[55] = new Rule(-23, new int[]{-24});
    rules[56] = new Rule(-24, new int[]{37,-11,38});
    rules[57] = new Rule(-24, new int[]{6});
    rules[58] = new Rule(-24, new int[]{8});
    rules[59] = new Rule(-24, new int[]{7});
    rules[60] = new Rule(-24, new int[]{5});
    rules[61] = new Rule(-12, new int[]{31,37,-11,38,-9});
    rules[62] = new Rule(-12, new int[]{31,37,-11,38,-9,32,-9});
    rules[63] = new Rule(-13, new int[]{33,37,-11,38,-9});
    rules[64] = new Rule(-14, new int[]{34,5,41});
    rules[65] = new Rule(-14, new int[]{34,5,42,13,41});
    rules[66] = new Rule(-15, new int[]{35,-11,41});
    rules[67] = new Rule(-15, new int[]{35,-11,42,13,41});
    rules[68] = new Rule(-15, new int[]{35,9,41});
    rules[69] = new Rule(-16, new int[]{36,41});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // start -> Program, OpenCurl, declarations, CloseCurl, EOF
#line 72 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                    { }
#line default
        break;
      case 3: // declarations -> instructions
#line 75 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                            { }
#line default
        break;
      case 4: // declarations -> declaration, declarations
#line 76 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                               { }
#line default
        break;
      case 5: // declaration -> Integer, declarationInt
#line 79 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                     { }
#line default
        break;
      case 6: // declaration -> Double, declarationDouble
#line 80 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                              { }
#line default
        break;
      case 7: // declaration -> Bool, declarationBool
#line 81 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                          { }
#line default
        break;
      case 8: // declarationInt -> Identifier, Semicolon
#line 84 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                      { Compiler.PushNode(new DeclarationNode(ExpressionType.Integer, ValueStack[ValueStack.Depth-2].String)); }
#line default
        break;
      case 9: // declarationInt -> Identifier, Comma, declarationInt
#line 85 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                        { Compiler.PushNode(new DeclarationNode(ExpressionType.Integer, ValueStack[ValueStack.Depth-3].String)); }
#line default
        break;
      case 10: // declarationInt -> error, Semicolon
#line 86 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                        { yyerrok(); }
#line default
        break;
      case 11: // declarationDouble -> Identifier, Semicolon
#line 89 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                         { Compiler.PushNode(new DeclarationNode(ExpressionType.Double, ValueStack[ValueStack.Depth-2].String)); }
#line default
        break;
      case 12: // declarationDouble -> Identifier, Comma, declarationDouble
#line 90 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                           { Compiler.PushNode(new DeclarationNode(ExpressionType.Double, ValueStack[ValueStack.Depth-3].String)); }
#line default
        break;
      case 13: // declarationDouble -> error, Semicolon
#line 91 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                           { yyerrok(); }
#line default
        break;
      case 14: // declarationBool -> Identifier, Semicolon
#line 94 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                       { Compiler.PushNode(new DeclarationNode(ExpressionType.Bool, ValueStack[ValueStack.Depth-2].String)); }
#line default
        break;
      case 15: // declarationBool -> Identifier, Comma, declarationBool
#line 95 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                       { Compiler.PushNode(new DeclarationNode(ExpressionType.Bool, ValueStack[ValueStack.Depth-3].String)); }
#line default
        break;
      case 16: // declarationBool -> error, Semicolon
#line 96 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                         { yyerrok(); }
#line default
        break;
      case 17: // instructions -> instructions, instruction
#line 99 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                        { BlockInstructionNode.InsertInstructionToTopBlock(); }
#line default
        break;
      case 18: // instructions -> /* empty */
#line 100 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
      { Compiler.PushNode(new BlockInstructionNode()); }
#line default
        break;
      case 19: // instruction -> blockInstruction
#line 103 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                               { }
#line default
        break;
      case 20: // instruction -> expression, Semicolon
#line 104 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                          { }
#line default
        break;
      case 21: // instruction -> ifInstruction
#line 105 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                   { }
#line default
        break;
      case 22: // instruction -> whileInstruction
#line 106 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                      { }
#line default
        break;
      case 23: // instruction -> inputInstruction
#line 107 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                      { }
#line default
        break;
      case 24: // instruction -> outputInstruction
#line 108 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                       { }
#line default
        break;
      case 25: // instruction -> returnInstruction
#line 109 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                       { }
#line default
        break;
      case 26: // instruction -> error, Semicolon
#line 110 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                     { yyerrok(); }
#line default
        break;
      case 27: // blockInstruction -> OpenCurl, instructions, CloseCurl
#line 113 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                   {  }
#line default
        break;
      case 28: // expression -> assignExpression
#line 116 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                              { }
#line default
        break;
      case 29: // assignExpression -> Identifier, Assign, assignExpression
#line 119 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                      { Compiler.PushNode(new AssignNode(ValueStack[ValueStack.Depth-3].String)); }
#line default
        break;
      case 30: // assignExpression -> logicalExpression
#line 120 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                         { }
#line default
        break;
      case 31: // logicalExpression -> logicalExpression, Or, relationExpression
#line 123 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                            { Compiler.PushNode(new LogicalExpressionNode(LogicalExpressionNode.Type.Or)); }
#line default
        break;
      case 32: // logicalExpression -> logicalExpression, And, relationExpression
#line 124 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                 { Compiler.PushNode(new LogicalExpressionNode(LogicalExpressionNode.Type.And)); }
#line default
        break;
      case 33: // logicalExpression -> relationExpression
#line 125 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                           { }
#line default
        break;
      case 34: // relationExpression -> relationExpression, Equals, addExpression
#line 128 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                             { Compiler.PushNode(new RelationExpressionNode(RelationExpressionNode.Type.Equals)); }
#line default
        break;
      case 35: // relationExpression -> relationExpression, NotEquals, addExpression
#line 129 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                    { Compiler.PushNode(new RelationExpressionNode(RelationExpressionNode.Type.NotEquals)); }
#line default
        break;
      case 36: // relationExpression -> relationExpression, GreaterThan, addExpression
#line 130 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                      { Compiler.PushNode(new RelationExpressionNode(RelationExpressionNode.Type.GreaterThan )); }
#line default
        break;
      case 37: // relationExpression -> relationExpression, GreaterOrEqual, addExpression
#line 131 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                         { Compiler.PushNode(new RelationExpressionNode(RelationExpressionNode.Type.GreaterOrEqual)); }
#line default
        break;
      case 38: // relationExpression -> relationExpression, LessThan, addExpression
#line 132 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                   { Compiler.PushNode(new RelationExpressionNode(RelationExpressionNode.Type.LessThan)); }
#line default
        break;
      case 39: // relationExpression -> relationExpression, LessOrEqual, addExpression
#line 133 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                      { Compiler.PushNode(new RelationExpressionNode(RelationExpressionNode.Type.LessOrEqual)); }
#line default
        break;
      case 40: // relationExpression -> addExpression
#line 134 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                       { }
#line default
        break;
      case 41: // addExpression -> addExpression, Plus, mulExpression
#line 137 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                 { Compiler.PushNode(new AddExpressionNode(AddExpressionNode.Type.Plus)); }
#line default
        break;
      case 42: // addExpression -> addExpression, Minus, mulExpression
#line 138 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                         { Compiler.PushNode(new AddExpressionNode(AddExpressionNode.Type.Minus)); }
#line default
        break;
      case 43: // addExpression -> mulExpression
#line 139 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                     { }
#line default
        break;
      case 44: // mulExpression -> mulExpression, Multiply, bitExpression
#line 143 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                     { Compiler.PushNode(new MulExpressionNode(MulExpressionNode.Type.Multiply)); }
#line default
        break;
      case 45: // mulExpression -> mulExpression, Divide, bitExpression
#line 144 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                          { Compiler.PushNode(new MulExpressionNode(MulExpressionNode.Type.Divide)); }
#line default
        break;
      case 46: // mulExpression -> bitExpression
#line 145 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                     { }
#line default
        break;
      case 47: // bitExpression -> bitExpression, BitwiseOr, unaryExpression
#line 149 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                        { Compiler.PushNode(new BitExpressionNode(BitExpressionNode.Type.Or)); }
#line default
        break;
      case 48: // bitExpression -> bitExpression, BitwiseAnd, unaryExpression
#line 150 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                { Compiler.PushNode(new BitExpressionNode(BitExpressionNode.Type.And)); }
#line default
        break;
      case 49: // bitExpression -> unaryExpression
#line 151 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                       { }
#line default
        break;
      case 50: // unaryExpression -> Minus, unaryExpression
#line 154 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                        { Compiler.PushNode(new UnaryExpressionNode(UnaryExpressionNode.Type.Minus)); }
#line default
        break;
      case 51: // unaryExpression -> BitwiseNegate, unaryExpression
#line 155 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                    { Compiler.PushNode(new UnaryExpressionNode(UnaryExpressionNode.Type.BitwiseNegate)); }
#line default
        break;
      case 52: // unaryExpression -> Negate, unaryExpression
#line 156 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                             { Compiler.PushNode(new UnaryExpressionNode(UnaryExpressionNode.Type.Negate)); }
#line default
        break;
      case 53: // unaryExpression -> OpenBracket, Integer, CloseBracket, unaryExpression
#line 157 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                       { Compiler.PushNode(new UnaryExpressionNode(UnaryExpressionNode.Type.IntConversion)); }
#line default
        break;
      case 54: // unaryExpression -> OpenBracket, Double, CloseBracket, unaryExpression
#line 158 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                      { Compiler.PushNode(new UnaryExpressionNode(UnaryExpressionNode.Type.DoubleConversion)); }
#line default
        break;
      case 55: // unaryExpression -> factorExpression
#line 159 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                       { }
#line default
        break;
      case 56: // factorExpression -> OpenBracket, expression, CloseBracket
#line 162 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                       { }
#line default
        break;
      case 57: // factorExpression -> IntegerLiteral
#line 163 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                         { Compiler.PushNode(new IntegerFactorNode(ValueStack[ValueStack.Depth-1].Integer)); }
#line default
        break;
      case 58: // factorExpression -> BoolLiteral
#line 164 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                      { Compiler.PushNode(new BoolFactorNode(ValueStack[ValueStack.Depth-1].Bool)); }
#line default
        break;
      case 59: // factorExpression -> DoubleLiteral
#line 165 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                        { Compiler.PushNode(new DoubleFactorNode(ValueStack[ValueStack.Depth-1].String)); }
#line default
        break;
      case 60: // factorExpression -> Identifier
#line 166 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                  { Compiler.PushNode(new IdentifierNode(ValueStack[ValueStack.Depth-1].String)); }
#line default
        break;
      case 61: // ifInstruction -> If, OpenBracket, expression, CloseBracket, instruction
#line 169 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                                   { Compiler.PushNode(new IfNode(false)); }
#line default
        break;
      case 62: // ifInstruction -> If, OpenBracket, expression, CloseBracket, instruction, Else, 
               //                  instruction
#line 170 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                                           { Compiler.PushNode(new IfNode(true)); }
#line default
        break;
      case 63: // whileInstruction -> While, OpenBracket, expression, CloseBracket, instruction
#line 173 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                                                         { Compiler.PushNode(new WhileNode()); }
#line default
        break;
      case 64: // inputInstruction -> Read, Identifier, Semicolon
#line 176 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                             { Compiler.PushNode(new ReadNode(ValueStack[ValueStack.Depth-2].String, false)); }
#line default
        break;
      case 65: // inputInstruction -> Read, Identifier, Comma, Hex, Semicolon
#line 177 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                           { Compiler.PushNode(new ReadNode(ValueStack[ValueStack.Depth-4].String, true)); }
#line default
        break;
      case 66: // outputInstruction -> Write, expression, Semicolon
#line 180 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                               { Compiler.PushNode(new WriteExpressionNode(false)); }
#line default
        break;
      case 67: // outputInstruction -> Write, expression, Comma, Hex, Semicolon
#line 181 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                             { Compiler.PushNode(new WriteExpressionNode(true)); }
#line default
        break;
      case 68: // outputInstruction -> Write, StringLiteral, Semicolon
#line 182 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                      { WriteStringNode.CreateWriteStringNodes(ValueStack[ValueStack.Depth-2].String); }
#line default
        break;
      case 69: // returnInstruction -> Return, Semicolon
#line 185 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"
                                     { Compiler.PushNode(new ReturnNode()); }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 190 "C:\Users\Mateusz\Documents\GitHub\mini-compiler\mini-compiler\kompilator.y"

public Parser(Scanner scnr) : base(scnr) { }
#line default
}
}
